# Generated by Django 5.2.8 on 2025-11-27 07:52

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
            ],
            options={
                'verbose_name': 'Kitchen Staff',
                'verbose_name_plural': 'Kitchen Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Restaurant Admin',
                'verbose_name_plural': 'Restaurant Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Super Admin',
                'verbose_name_plural': 'Super Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
            ],
            options={
                'verbose_name': 'Waiter',
                'verbose_name_plural': 'Waiters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
