# Generated by Django 5.2.8 on 2025-11-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kitchenstaff_manager_restaurantadmin_superadmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitchenStaff',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='RestaurantAdmin',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RESTAURANT_ADMIN', 'Restaurant Owner'), ('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('KITCHEN', 'Kitchen Staff')], default='RESTAURANT_ADMIN', max_length=20),
        ),
    ]
