"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j)nvx2*6z!b5!v2b84q5xw9*ndc!mtaeko#e$(w0@wh+xqm8(@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party libraries (install agar nahi kiya to: pip install djangorestframework django-cors-headers)
    "jazzmin",
    'rest_framework',
    'rest_framework.authtoken',  # <--- Ye line add karein
    'corsheaders',

    # Hamari Apps
    'tenants',
    'accounts',
    'menu',
    'orders',
    'payments',
    'analytics',
]

# Custom User Model (Ye line sabse neeche add karein)
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add this at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# React/Next.js ko allow karne ke liye
CORS_ALLOW_ALL_ORIGINS = True  # Development ke liye True rakhein
ROOT_URLCONF = 'core.urls'

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000", 
#     "http://127.0.0.1:3000",
# ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise Storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'








# backend/core/settings.py ke last mein add karein

# RAZORPAY_KEY_ID = "rzp_test_YOUR_KEY_HERE"  # Yahan apni Key ID dalein
# RAZORPAY_KEY_SECRET = "YOUR_SECRET_HERE"    # Yahan Secret dalein




# REST Framework Settings (Security relax karne ke liye)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}




JAZZMIN_SETTINGS = {
    "site_title": "Resto SaaS Admin",
    "site_header": "SmartDine Admin",
    "welcome_sign": "Welcome to SmartDine Control Panel",

    "icons": {
        "accounts.User": "fas fa-users-cog",
    },

    "order_with_respect_to": ["accounts", "tenants", "menu", "orders", "payments"],

    "side_menu": {
        "items": [
            # USERS MAIN MENU
            {
                "label": "Users",
                "app": "accounts",
                "icon": "fas fa-user",
                "models": [
                    {"label": "All Users", "name": "accounts.user"},
                    {"label": "Super Admins", "name": "Super Admins"},
                    {"label": "Restaurant Admins", "name": "Restaurant Admins"},
                    {"label": "Managers", "name": "Managers"},
                    {"label": "Waiters", "name": "Waiters"},
                    {"label": "Kitchen Staff", "name": "Kitchen Staff"},
                ],
            },
        ]
    }
}
